<main class="main-chat">
<h1 hidden>Le chat</h1>
<aside class="categories">
    <h2>Les catégories</h2>
    <ul class="navbar-categories">
        <?php
        foreach ($categories as $category) {
        ?>
            <li><?= $category->getName() ?></li>
            <ul class="navbar-salons">
                <?php

                $sm = new SalonManager;
                $salons = $sm->findByCategory($category->getId());

                foreach ($salons as $salon) {

                ?>
                    <li><a href="index.php?route=chat&salon=<?= $salon->getId() ?>"><?= $salon->getName() ?></a></li>
                <?php
                }
                ?>
            </ul>
        <?php
        }
        ?>
    </ul>
</aside>
<div class="background-chat">
<section class="chat-container">
    <h2>Le chat</h2>
    <p class="chat-container-chose">Sélectionnez un salon pour envoyer un message</p>
</section>
</div>

<section class="pub">
    <article class="pub-card">
        <div class="pub-img-container">
            <img src="../style/img/attrape-soleil.jpg" alt="attrape con">
        </div>
        <p>Attrape soleil</p>
        <p>100€</p>
    </article>
    <article class="pub-card">
        <div class="pub-img-container">
            <img src="../style/img/diffuseur.jpg" alt="diffuseur pour voiture">
        </div>
        <p>diffuseur huiles essentielles pour voiture</p>
        <p class="barre">9.90€</p>
        <p class="prix">8.40€</p>
    </article>
    <article class="pub-card">
        <div class="pub-img-container">
            <img src="https://www.chakra.fr/176-large_default/7-mini-pierres-de-soulagement-chakra.jpg" alt="pierres">
        </div>
        <p>mini pierres de soulagement chakra</p>
        <p class="barre">19.95€</p>
        <p class="prix">16.16€</p>
    </article>
</section>
</main>
