<main class="main-connexion">

    <section class="connexion-container">

        <h1>Connexion</h1>

        <form action="index.php?route=check-signin" method="post">

            <label for="email">email</label>
            <input type="email" name="email" id="email" required>
            <label for="password">password</label>
            <input type="password" name="password" id="password" required>
            <button type="submit">connexion</button>

        </form>
    </section>

</main>