<main class="main-inscription">

<section class="inscription-container">

<h1>Inscription</h1>

<form action="index.php?route=check-signup" method="post">

<label for="email">email</label>
<input type="email" name="email" id="email">
<label for="name">name</label>
<input type="text" name="name" id="name">
<label for="password">password</label>
<input type="password" name="password" id="password">
<button type="submit">rejoindre la communauté bienveillante</button>

</form>

</section>

</main>