<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="concurrent de discord">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="style/style.css">
    <title>Distorsion</title>
</head>
<body>
    <header>
        <nav>
            <ul class="header-navbar">
                <li>
                    <a href="index.php">
                        <img src="style/img/logo.png" alt="logo distorsion">
                    </a>    
                </li>
                <div class="navbar-right">
                <li>
                    <a href="index.php?route=chat">
                        chat
                    </a>
                </li>
                
                <li>
                    <a href="index.php?route=a-propos">
                        à propos
                    </a>
                </li>
                <?php if(empty($_SESSION)) {?>
                <li>
                    <a href="index.php?route=connexion">
                        connexion
                    </a>
                </li>
                <?php } else { ?>
                <li><a href="index.php?route=user-profil">espace perso</a></li>
                    <li><a href="index.php?route=deconnexion">déconnexion</a></li>
                    <?php }?>
                    <li>
                    <a href="index.php?route=inscription">
                        inscription
                    </a>
                </li>
                </div>
            </ul>
        </nav>
    </header>
    
        <?php

        require "templates/$route.phtml";

        ?>
    
</body>
</html>