<main class="main-chat">

<h1 hidden>Le chat</h1>

<aside class="categories">
    <h2>Les catégories</h2>
    <ul class="navbar-categories">
        <?php
        foreach ($categories as $category) {
        ?>
            <li><?= $category->getName() ?></li>
            <ul class="navbar-salons">
                <?php


                $salons = $sm->findByCategory($category->getId());

                foreach ($salons as $salon) {

                ?>
                    <li <?php if(isset($_GET["salon"]) && $_GET["salon"] === (string)$salon->getId()){
                        ?>class="salon-active"<?php
                    } 
                    ?>>
                        <a href="index.php?route=chat&salon=<?= $salon->getId() ?>"><?= $salon->getName() ?>
                        </a>
                    </li>
                <?php
                }
                ?>
            </ul>
        <?php
        }
        ?>
    </ul>
    </aside>


<div class="background-chat">
<section class="chat-container">
    <div class="flex-top-container">
    <h2>Salon <?= $sm->findOne($id)->getName() ?> </h2>
    <div class="messages-container">
    <?php
    foreach ($messages as $message) {
    ?>
        <article class="salons-message">
        <p class="salons-message-date">Le <?= $message->getCreatedAt()->format('d/m/Y') ?> à <?= $message->getCreatedAt()->format('h:i:s') ?></p>
        <div class="message-user">
        <p class="salons-message-content"><?= $message->getContent() ?></p>
        <p class="salons-message-user"><?= $message->getAuthor()->getName() ?></p>
        </div>
        </article>
    <?php
    }
    ?>
    </div>
    </div>
    <form class="chat-form" action="index.php?route=check-message&salon=<?= $id ?>" method="post">
        <div class="field">
            <label for="message">Message</label>
            <textarea name="message" id="message"></textarea>
        </div>
        <button type="submit">Envoyer</button>
    </form>
</section>
</div>

<section class="pub">
    <article class="pub-card">
        <div class="pub-img-container">
            <img src="../style/img/attrape-soleil.jpg" alt="attrape con">
        </div>
        <p>Attrape soleil</p>
        <p>100€</p>
    </article>
    <article class="pub-card">
        <div class="pub-img-container">
            <img src="../style/img/diffuseur.jpg" alt="diffuseur pour voiture">
        </div>
        <p>diffuseur huiles essentielles pour voiture</p>
        <p class="barre">9.90€</p>
        <p class="prix">8.40€</p>
    </article>
    <article class="pub-card">
        <div class="pub-img-container">
            <img src="https://www.chakra.fr/176-large_default/7-mini-pierres-de-soulagement-chakra.jpg" alt="pierres">
        </div>
        <p>mini pierres de soulagement chakra</p>
        <p class="barre">19.95€</p>
        <p class="prix">16.16€</p>
    </article>
</section>
</main>