<main>
    <section>
       <h2>Bienvenue <?= $user->getName()?></h2>
    
    <p>Email du compte : <?= $user->getEmail() ?></p> 
    </section>
    <section>
        
        <table>
            <thead>
                <th>
                    #
                </th>
                <th>
                    Salon
                </th>
                <th>
                    Contenu
                </th>
                
                
                
            </thead>
            <tbody>
                <tr>
                <td></td>
            </tr>
            </tbody>
            
        </table>
        
        
    </section>
    
    
    
    
    
</main>