<main class="espace-perso-main">
    <section class="espace-perso-section-title">
        <h1>Bienvenue dans ton espace cosmique <strong><?= $user->getName() ?></strong></h1>

        <p>Email du compte : <strong><?= $user->getEmail() ?></strong></p>
    </section>
    <section class="espace-perso-section-messages">
        <h2>Voici toutes tes fabuleuses participations à notre communauté:</h2>
        <table>
            <thead>
                <th>
                    #
                </th>
                <th>
                    Salon
                </th>
                <th>
                    Contenu
                </th>



            </thead>
            <tbody>
                <?php foreach ($userMessages as $messages) { ?>
                    <tr>

                        <td><?= $messages->getId() ?></td>
                        <td><a href="index.php?route=chat&salon=<?= $messages->getSalon()->getId() ?>"><?= $messages->getSalon()->getName() ?></a></td>
                        <td><?= $messages->getContent() ?></td>

                    </tr>
                <?php } ?>
            </tbody>

        </table>


    </section>





</main>